#!/usr/bin/env bash
# Write per-coin testnet config + systemd unit and start the daemons.
#
# Port map matches the Eliopool testnet stack
# so that MPOS and Eliopool can share testnet RPCs.
set -euo pipefail

say() { printf '\033[1;33m   %s\033[0m\n' "$*"; }

DATA_ROOT="${MPOS_DATA_ROOT:-/var/lib/blakestream-mpos}"
LOG_ROOT="${MPOS_LOG_ROOT}/daemons"
mkdir -p "$DATA_ROOT" "$LOG_ROOT"

NODE_RPC_USER="${MPOS_NODE_RPC_USER:-blakestream}"
NODE_RPC_PASS="${MPOS_NODE_RPC_PASS:-blakestream-testnet}"

# Same testnet ports as Eliopool's deploy-full-testnet-stack.sh
COIN_TABLE=(
    # key|conf|datadir|rpc|p2p|peer-rpc|peer-p2p|daemon|cli
    "blakecoin|blakecoin.conf|blakecoin|29332|29777|29333|29778|blakecoind|blakecoin-cli"
    "blakebitcoin|blakebitcoin.conf|blakebitcoin|29112|29113|29114|29115|blakebitcoind|blakebitcoin-cli"
    "electron|electron.conf|electron|26852|26853|26854|26855|electrond|electron-cli"
    "lithium|lithium.conf|lithium|32004|32000|32005|32001|lithiumd|lithium-cli"
    "photon|photon.conf|photon|28998|28992|28999|28993|photond|photon-cli"
    "universalmolecule|universalmolecule.conf|universalmol|29738|29449|29739|29450|universalmoleculed|universalmolecule-cli"
)

ensure_user() {
    if ! id -u blakestream-mpos >/dev/null 2>&1; then
        useradd --system --home /nonexistent --shell /usr/sbin/nologin blakestream-mpos
    fi
}
ensure_user

write_conf() {
    local datadir="$1" rpcport="$2" p2pport="$3" peer_p2p="$4"
    local conf_path="$5"
    cat > "$conf_path" <<EOF
# Generated by Blakestream-MPOS deploy-bundle
testnet=1
rpcuser=${NODE_RPC_USER}
rpcpassword=${NODE_RPC_PASS}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=${rpcport}
port=${p2pport}
listen=1
server=1
daemon=0
txindex=1
fallbackfee=0.0001
discover=0
listenonion=0
upnp=0
maxtipage=3153600000
dnsseed=0
fixedseeds=0
addnode=127.0.0.1:${peer_p2p}
EOF
    chmod 640 "$conf_path"
}

write_unit() {
    local key="$1" daemon="$2" datadir="$3" conf_name="$4" suffix="$5"
    local unit="/etc/systemd/system/blakestream-mpos-${key}${suffix}.service"
    cat > "$unit" <<EOF
[Unit]
Description=Blakestream-MPOS ${key}${suffix} testnet daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=blakestream-mpos
Group=blakestream-mpos
WorkingDirectory=${MPOS_INSTALL_ROOT}
ExecStart=${MPOS_INSTALL_ROOT}/bin/${daemon} -conf=${datadir}/${conf_name} -datadir=${datadir}
StandardOutput=append:${LOG_ROOT}/${key}${suffix}.stdout
StandardError=append:${LOG_ROOT}/${key}${suffix}.stderr
Restart=always
RestartSec=5
LimitNOFILE=4096

[Install]
WantedBy=multi-user.target
EOF
}

for row in "${COIN_TABLE[@]}"; do
    IFS='|' read -r key conf coin_dir rpc p2p peer_rpc peer_p2p daemon cli <<< "$row"
    primary_dir="${DATA_ROOT}/${coin_dir}"
    peer_dir="${DATA_ROOT}/${coin_dir}-peer"
    mkdir -p "$primary_dir" "$peer_dir"
    write_conf "$primary_dir" "$rpc" "$p2p" "$peer_p2p" "$primary_dir/$conf"
    write_conf "$peer_dir"    "$peer_rpc" "$peer_p2p" "$p2p" "$peer_dir/$conf"
    chown -R blakestream-mpos:blakestream-mpos "$primary_dir" "$peer_dir"
    write_unit "$key" "$daemon" "$primary_dir" "$conf" ""
    write_unit "$key" "$daemon" "$peer_dir"    "$conf" "-peer"
done

chown -R blakestream-mpos:blakestream-mpos "$LOG_ROOT"
systemctl daemon-reload

say "starting all 12 daemons (primary + peer per chain)"
for row in "${COIN_TABLE[@]}"; do
    IFS='|' read -r key _ _ _ _ _ _ _ _ <<< "$row"
    systemctl enable --now "blakestream-mpos-${key}.service"
    systemctl enable --now "blakestream-mpos-${key}-peer.service"
done

# Wave 3: wait for blakecoin RPC to come up — fail HARD if it doesn't.
# Previously the loop fell through silently if all 40 attempts failed,
# letting subsequent install steps proceed against a dead daemon and
# producing a confusing failure 30 lines later. Now exits non-zero so
# the deploy bundle aborts at the actual root cause.
say "waiting for parent-chain RPC on 29332 (40 attempts × 0.5s = 20s)"
RPC_OK=0
for attempt in $(seq 1 40); do
    if curl -fsSL --max-time 2 -u "${NODE_RPC_USER}:${NODE_RPC_PASS}" \
        --data '{"jsonrpc":"1.0","id":"deploy","method":"getblockcount"}' \
        -H 'content-type: text/plain' http://127.0.0.1:29332/ >/dev/null 2>&1; then
        say "blakecoin RPC OK on attempt ${attempt}"
        RPC_OK=1
        break
    fi
    sleep 0.5
done
if [ "$RPC_OK" != "1" ]; then
    echo "ERROR: blakecoin RPC never came up on 127.0.0.1:29332" >&2
    echo "       last 30 lines of journalctl -u blakestream-mpos-blakecoin.service:" >&2
    journalctl -u blakestream-mpos-blakecoin.service -n 30 --no-pager >&2 || true
    exit 1
fi
