#!/usr/bin/env bash
# Install conservative MariaDB tuning for MPOS share/accounting workloads.
set -euo pipefail

say() { printf '\033[1;33m   %s\033[0m\n' "$*"; }
warn() { printf '\033[1;31m   warning: %s\033[0m\n' "$*" >&2; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=1
fi

require_positive_int() {
    local name="$1" value="$2"
    [[ "$value" =~ ^[1-9][0-9]*$ ]] || die "${name} must be a positive integer MiB value"
}

mem_total_mb() {
    awk '/^MemTotal:/ { print int($2 / 1024); exit }' /proc/meminfo
}

choose_buffer_pool_mb() {
    local total_mb="$1" min_mb max_mb chosen_mb

    min_mb="${MPOS_MARIADB_BUFFER_POOL_MIN_MB:-512}"
    max_mb="${MPOS_MARIADB_BUFFER_POOL_MAX_MB:-4096}"
    require_positive_int MPOS_MARIADB_BUFFER_POOL_MIN_MB "$min_mb"
    require_positive_int MPOS_MARIADB_BUFFER_POOL_MAX_MB "$max_mb"
    [ "$min_mb" -le "$max_mb" ] || die "MPOS_MARIADB_BUFFER_POOL_MIN_MB must be less than or equal to MPOS_MARIADB_BUFFER_POOL_MAX_MB"

    if [ -n "${MPOS_MARIADB_BUFFER_POOL_MB:-}" ]; then
        require_positive_int MPOS_MARIADB_BUFFER_POOL_MB "$MPOS_MARIADB_BUFFER_POOL_MB"
        printf '%s\n' "$MPOS_MARIADB_BUFFER_POOL_MB"
        return
    fi

    if [ -z "${MPOS_MARIADB_BUFFER_POOL_MIN_MB:-}" ] && [ "$total_mb" -lt 2048 ]; then
        min_mb=256
    fi

    chosen_mb=$(( total_mb / 4 ))
    [ "$chosen_mb" -lt "$min_mb" ] && chosen_mb="$min_mb"
    [ "$chosen_mb" -gt "$max_mb" ] && chosen_mb="$max_mb"
    printf '%s\n' "$chosen_mb"
}

choose_log_file_mb() {
    local buffer_mb="$1" chosen_mb

    if [ -n "${MPOS_MARIADB_LOG_FILE_MB:-}" ]; then
        require_positive_int MPOS_MARIADB_LOG_FILE_MB "$MPOS_MARIADB_LOG_FILE_MB"
        printf '%s\n' "$MPOS_MARIADB_LOG_FILE_MB"
        return
    fi

    chosen_mb=256
    if [ "$buffer_mb" -ge 4096 ]; then
        chosen_mb=1024
    elif [ "$buffer_mb" -ge 2048 ]; then
        chosen_mb=512
    fi
    printf '%s\n' "$chosen_mb"
}

validate_mariadb_config() {
    local server_bin=""

    if command -v mariadbd >/dev/null 2>&1; then
        server_bin="$(command -v mariadbd)"
    elif command -v mysqld >/dev/null 2>&1; then
        server_bin="$(command -v mysqld)"
    else
        warn "mariadbd/mysqld not found; skipping config validation"
        return 0
    fi

    "$server_bin" --verbose --help >/dev/null 2>/tmp/blakestream-mariadb-config-check.log
}

query_mariadb_variable() {
    local name="$1"
    mariadb -N -B -e "SHOW GLOBAL VARIABLES LIKE '${name}';" 2>/dev/null | awk '{print $2}'
}

TOTAL_MB="$(mem_total_mb)"
[ -n "$TOTAL_MB" ] || die "cannot read MemTotal from /proc/meminfo"

BUFFER_POOL_MB="$(choose_buffer_pool_mb "$TOTAL_MB")"
LOG_FILE_MB="$(choose_log_file_mb "$BUFFER_POOL_MB")"

CONF_DIR=/etc/mysql/mariadb.conf.d
CONF_FILE="${CONF_DIR}/99-blakestream-pool.cnf"
TMP_CONF="$(mktemp)"
trap 'rm -f "$TMP_CONF" "${BACKUP_CONF:-}"' EXIT

cat > "$TMP_CONF" <<EOF
# Generated by Blakestream-MPOS deploy/update.
# MPOS keeps recent share/accounting data hot; a larger InnoDB buffer pool
# prevents dashboard, PPLNS, and archive-prune queries from repeatedly
# reading the same rows from disk. The default caps leave RAM for daemon
# containers; override with MPOS_MARIADB_BUFFER_POOL_MB when needed.
# Do not set innodb_buffer_pool_instances here; MariaDB ignores/removes it
# across newer supported releases, while older releases run safely without it.
[mysqld]
innodb_buffer_pool_size=${BUFFER_POOL_MB}M
innodb_log_file_size=${LOG_FILE_MB}M
innodb_buffer_pool_dump_at_shutdown=ON
innodb_buffer_pool_load_at_startup=ON
EOF

if [ "$DRY_RUN" = "1" ]; then
    say "MariaDB pool tuning dry run (${TOTAL_MB} MiB RAM detected)"
    cat "$TMP_CONF"
    exit 0
fi

install -d -o root -g root -m 0755 "$CONF_DIR"

if [ -f "$CONF_FILE" ] && cmp -s "$TMP_CONF" "$CONF_FILE"; then
    say "MariaDB pool tuning already current (${BUFFER_POOL_MB}M buffer pool, ${LOG_FILE_MB}M redo log)"
else
    say "installing MariaDB pool tuning (${BUFFER_POOL_MB}M buffer pool, ${LOG_FILE_MB}M redo log)"
    BACKUP_CONF=""
    if [ -f "$CONF_FILE" ]; then
        BACKUP_CONF="$(mktemp)"
        cp -p "$CONF_FILE" "$BACKUP_CONF"
    fi
    install -o root -g root -m 0644 "$TMP_CONF" "$CONF_FILE"

    if ! validate_mariadb_config; then
        warn "MariaDB config validation failed"
        cat /tmp/blakestream-mariadb-config-check.log >&2 || true
        if [ -n "$BACKUP_CONF" ]; then
            install -o root -g root -m 0644 "$BACKUP_CONF" "$CONF_FILE"
        else
            rm -f "$CONF_FILE"
        fi
        exit 1
    fi

    if [ "${MPOS_MARIADB_RESTART:-1}" = "1" ]; then
        say "restarting MariaDB to apply pool tuning"
        systemctl restart mariadb
    else
        warn "MPOS_MARIADB_RESTART=0; tuning installed but not active until MariaDB restarts"
    fi
fi

if systemctl is-active --quiet mariadb; then
    active_buffer="$(query_mariadb_variable innodb_buffer_pool_size || true)"
    active_log="$(query_mariadb_variable innodb_log_file_size || true)"
    if [ -n "${active_buffer:-}" ] || [ -n "${active_log:-}" ]; then
        say "MariaDB active tuning: innodb_buffer_pool_size=${active_buffer:-unknown}, innodb_log_file_size=${active_log:-unknown}"
    fi
fi
